.SHELLFLAGS = -c

include shared_vars.mk

all:
	$(MAKE) -f "$(R_HOME)/etc$(R_ARCH)/Makeconf" -f "$(SRC)/MakefileNested.win" all
    
configure:
	$(MAKE) -f "$(R_HOME)/etc$(R_ARCH)/Makeconf" -f "$(SRC)/MakefileNested.win" configure

clean:
	$(MAKE) -f "$(R_HOME)/etc$(R_ARCH)/Makeconf" -f "$(SRC)/MakefileNested.win" clean
	rm -rf \
		build \
		probabilistic.Rcheck \
		probabilistic*.tar.gz

